{
 "title": "Optimize Live - HPA",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "workload", "label": "Workload", "query": { "query": "label_values(workload)" } },
   { "name": "cpuRisk", "label": "CPU Tolerance", "query": { "query": "label_values(cpuRisk)" } },
   { "name": "memoryRisk", "label": "Memory Tolerance", "query": { "query": "label_values(memoryRisk)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"margin-top:2em;text-align:center;\">\n  <h1 >\n    StormForge Optimize Live\n  </h1>\n  <h3>\n    CPU Recommendations for ${workload}\n  </h3>\n</div>\n"
   }
  },
  {
   "title": "Current Settings",
   "type": "stat",
   "description": "Currently configured requests and limits, per container. Currently configured HPA target utilization for the workload.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (workload,namespace,resource,container) (requests{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"cpu\"})",
     "legendFormat": "CPU Requests ({{container}})"
    },
    {
     "expr": "avg by (workload,namespace,resource,container) (limits{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"cpu\"})",
     "legendFormat": "CPU Limits ({{container}})"
    },
    {
     "expr": "avg(hpa{namespace=\"$namespace\",metric_name=\"cpu\",metric_target_type=\"utilization\",horizontalpodautoscaler=\"$workload\",application_name=\"$application\"})",
     "legendFormat": "HPA Target"
    }
   ]
  },
  {
   "title": "Recommended Settings",
   "type": "stat",
   "description": "Recommended requests and limits, per container. Recommended HPA target utilization for the workload.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (candidate) (recommendation{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"cpu\",metric=\"requests\",cpuRisk=\"$cpuRisk\"})",
     "legendFormat": "CPU Requests ({{container}})"
    },
    {
     "expr": "avg without (candidate) (recommendation{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"cpu\",metric=\"limits\",cpuRisk=\"$cpuRisk\"})",
     "legendFormat": "CPU Limits ({{container}})"
    },
    {
     "expr": "avg without (candidate) (recommendation{metric=\"target\",workload=~\"$workload\",namespace=~\"$namespace\",cpuRisk=\"$cpuRisk\"})",
     "legendFormat": "HPA Target"
    }
   ]
  },
  {
   "title": "Projected CPU Requests Savings",
   "type": "gauge",
   "description": "Average CPU request savings, as a percentage difference, over the time period selected, had the recommended settings been in use",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1\n-\nmax by (namespace,workload) (avg_over_time(\n  recommendation{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"cpu\",metric=\"requests\",cpuRisk=\"$cpuRisk\"}[$__range]))\n/\nmax by (namespace,workload) (avg_over_time(\n  requests{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"cpu\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Projected CPU Core-Requests Savings",
   "type": "stat",
   "description": "Average projected CPU request savings, in cores, over the time period selected, had the recommended settings been in use",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((\n  max by (workload,namespace) (replicas{workload=~\"$workload\",namespace=~\"$namespace\"})\n  *\n  ( max by (workload,namespace) (requests{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"cpu\"}) \n    -\n    max by (workload,namespace) (recommendation{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"cpu\",metric=\"requests\",cpuRisk=\"$cpuRisk\"}))\n)[$__range:$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Utilization and Requests (CPU)",
   "type": "timeseries",
   "description": "Shows the sum total CPU utilization, sum total CPU requests, and sum total projected CPU requests after applying the recommended settings. This view includes and sums totals across all replicas.\n\nRed-shaded area represents over-provisioned requests, and blue-shaded area represents under-provisioned requests, relative to Optimize Live's recommendations.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg by (workload,namespace,resource) (sum by (workload,namespace,resource) (usage{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"cpu\"}))",
     "legendFormat": "Cumulative CPU Utilization"
    },
    {
     "expr": "max by(namespace,workload) (requests{namespace=\"$namespace\",workload=\"$workload\",resource=\"cpu\"}) * max by(namespace,workload) (replicas{namespace=\"$namespace\",workload=\"$workload\"})",
     "legendFormat": "Cumulative CPU Requests (current settings)"
    },
    {
     "expr": "max by(workload, namespace) (recommendation{metric=\"requests\",workload=~\"$workload\",namespace=~\"$namespace\",resource=\"cpu\",cpuRisk=\"$cpuRisk\"}) * max by (workload, namespace) (replicas{workload=~\"$workload\",namespace=~\"$namespace\"})",
     "legendFormat": "Cumulative CPU Requests Projection (recommended settings)"
    },
    {
     "expr": "avg(replicas{workload=~\"$workload\",namespace=~\"$namespace\"})",
     "legendFormat": "Number of Replicas"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<div style=\"margin-top:2em;text-align:center;\">\n  <h3>\n    Memory Recommendations for ${workload}\n  </h3>\n</div>"
   }
  },
  {
   "title": "Current Settings",
   "type": "stat",
   "description": "Currently configured requests and limits, per container.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (workload,namespace,resource,container) (requests{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"memory\"})",
     "legendFormat": "Memory Requests ({{container}})"
    },
    {
     "expr": "avg by (workload,namespace,resource,container) (limits{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"memory\"})",
     "legendFormat": "Memory Limits ({{container}})"
    }
   ]
  },
  {
   "title": "Recommended Settings",
   "type": "stat",
   "description": "Recommended requests and limits, per container.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (candidate) (recommendation{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"memory\",metric=\"requests\",cpuRisk=\"$cpuRisk\"})",
     "legendFormat": "Memory Requests ({{container}})"
    },
    {
     "expr": "avg without (candidate) (recommendation{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"memory\",metric=\"limits\",cpuRisk=\"$cpuRisk\"})",
     "legendFormat": "Memory Limits ({{container}})"
    }
   ]
  },
  {
   "title": "Projected Memory Requests Savings",
   "type": "gauge",
   "description": "Average projected memory request savings, as a percentage, over the time period selected, had the recommended settings been in use",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1\n-\nmax by (namespace,workload) (avg_over_time(\n  recommendation{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"memory\",metric=\"requests\",cpuRisk=\"$cpuRisk\"}[$__range]))\n/\nmax by (namespace,workload) (avg_over_time(\n  requests{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"memory\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Projected Memory Byte-Requests Savings",
   "type": "stat",
   "description": "Average projected memory request savings, in bytes, over the time period selected, had the recommended settings been in use",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((\n  max by (workload,namespace) (replicas{workload=~\"$workload\",namespace=~\"$namespace\"})\n  *\n  ( max by (workload,namespace) (requests{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"memory\"}) \n    -\n    max by (workload,namespace) (recommendation{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"memory\",metric=\"requests\",cpuRisk=\"$cpuRisk\"}))\n)[$__range:$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Utilization and Requests (Memory)",
   "type": "timeseries",
   "description": "Shows the sum total memory utilization, sum total memory requests, and sum total projected memory requests after applying the recommended settings. This view includes and sums totals across all replicas.\n\nRed-shaded area represents over-provisioned requests, and blue-shaded area represents under-provisioned requests, relative to Optimize Live's recommendations.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (workload,namespace,resource) (sum by (workload,namespace,resource) (usage{workload=~\"$workload\",namespace=~\"$namespace\",resource=\"memory\"}))",
     "legendFormat": "Cumulative Memory Utilization"
    },
    {
     "expr": "avg by(workload,namespace) (requests{namespace=\"$namespace\",workload=\"$workload\",resource=\"memory\"}) * max by(namespace,workload) (replicas{namespace=\"$namespace\",workload=\"$workload\"})",
     "legendFormat": "Cumulative Memory Requests (current settings)"
    },
    {
     "expr": "max by(workload, namespace) (recommendation{metric=\"requests\",workload=~\"$workload\",namespace=~\"$namespace\",resource=\"memory\",memoryRisk=\"$memoryRisk\"}) * max by (workload, namespace) (replicas{workload=~\"$workload\",namespace=~\"$namespace\"})",
     "legendFormat": "Cumulative Memory Requests Projection (recommended settings)"
    },
    {
     "expr": "avg(replicas{workload=~\"$workload\",namespace=~\"$namespace\"})",
     "legendFormat": "Number of Replicas"
    }
   ]
  }
 ]
}